### ISSUE TITLE
Does FragPipe-Analyst support multi-fraction runs?

### ISSUE THREAD

**Issue by TeckYewLow** [Nesvilab/FragPipe-Analyst-doc#10]
Hi,

I am playing around with a label-free DDA datasets which contains many samples and each sample is fractionated by basic C18 into many fractions. This is quite different from the example given in the tutorial where each samples comprise one LC-MS run. How can I configure the experiment annotation file to allow FragPipe-Analyst analysis?

Best,

Teck

**Comment by TeckYewLow** [comment]
I tried to run it on the https://fragpipe-analyst.org/ server. I got an error message, i.e.,

#error in evaluating the argument 'x' in selecting a method for function 'nrow': error in evaluating the argument 'x' in selecting a method for function 'assay': duplicate 'row.names' are not allowed

**Comment by hsiaoyi0504** [comment]
Duplicated as MonashProteomics/FragPipe-Analyst#79.

**Comment by hsiaoyi0504** [comment]
From your result, fractions are combined into one in the combined_protein file. So you will need to only keep one row for all fractions from the same sample. I emailed the modified version to @alyssaxin already. Note that I am not sure if you do have that many replicates.
