### ISSUE TITLE
got an error while running

### ISSUE THREAD

**Issue by punshah1** [Nesvilab/FragPipe-Analyst-doc#11]
An error has occurred. Check your logs or contact the app author for clarification.

some plots worked like protein number and sample coverage but result table had an error. 
can someone help me

**Comment by hsiaoyi0504** [comment]
@punshah1 Can you upload or send me yihsiao@umich.edu your file to take a look? It's hard to know what kind of issue you met without further information.

**Comment by hsiaoyi0504** [comment]
Close since no response.
