### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by tygrad** [Nesvilab/FragPipe-Analyst-doc#14]
I uploaded combined. protein tsv and experiment annotation and tried to run the analysis but says run error. After several attempts, it says disconnected from server. I tried to reload but failed

**Comment by hsiaoyi0504** [comment]
@tygrad Can you send us further information to my email? yihsiao@umich.edu
It's kind of hard to help if that's the only information shared with us.

**Comment by hsiaoyi0504** [comment]
Closed since no response.
