### ISSUE TITLE
Error when trying to view interactive volcano plot

### ISSUE THREAD

**Issue by MTM09386** [Nesvilab/FragPipe-Analyst-doc#15]
Hi, 

I am making this in response to comment in https://github.com/Nesvilab/FragPipe-Analyst/issues/7

When I click a specific point in the results table, it is not highlighted in the volcano plot. Instead I see the following:
![Unknown_error](https://github.com/Nesvilab/FragPipe-Analyst/assets/140008083/d5757298-ded4-440d-8144-c8ee252beba5)

This also happens if I try to use pathway enrichment or molecular function.

I get the same error whether I am using my data or the example data provided.

https://creightonuniv-my.sharepoint.com/:u:/g/personal/mtm09386_creighton_edu/Ec9bZqCaLZdOo2Du-vtaTBQBcOUA5ALomfb02MIDhoUdGw?e=Nlaxwy

https://creightonuniv-my.sharepoint.com/:u:/g/personal/mtm09386_creighton_edu/EW5Okz4mBN5Li3thvdIymswBTCbPdzU4SWGpLeOTkJOOkQ?e=lhrtQ8

Thank you,

Molly

**Comment by hsiaoyi0504** [comment]
@MTM09386 Thanks for catching that. I updated the dev server to v0.26. Things should be good now.
The changes also haven't been deployed to the production server I think. Please let us know if there is still any issue. Thanks.
