### ISSUE TITLE
Disconnected from Server

### ISSUE THREAD

**Issue by jjGG** [Nesvilab/FragPipe-Analyst-doc#16]
Hello FragPipe Analyst developers

We would like to use FragPipe Analyst in our courses. We are trying to get a hand on it. We would like to use it for DIA data (protein and peptide). 
Often we have difficulties to use it because, as soon as I press "Run" I get: "Disconnected from the server". -> reload. And this multiple times. 

Is there something that I am doing wrong? or is this on your side with limited compute resources?
I cannot really nail it. I am not sure if it is because of the (potentially wrong) input?

Update:
This happens always immediately after pressing RUN. But only for the DIA analysis. I can successfully run FP-Analyst for LFQ-DDA data.

![image](https://github.com/Nesvilab/FragPipe-Analyst/assets/4902603/c72b5303-fefa-477b-a16e-fc075c7bbc83)

bes regards
jonas

**Comment by hsiaoyi0504** [comment]
@jjGG I think it might be an issue of your input file. Would you mind share it will me so I can take a look? yihsiao@umich.edu

**Comment by hsiaoyi0504** [comment]
@jjGG I am going to close this since no further reponse. From what I remembered, it might because you upload a wrong experiment_annotation.tsv. Some users accidentally uploaded the manifest instead and see such error.
