### ISSUE TITLE
Error occured

### ISSUE THREAD

**Issue by Amelia811** [Nesvilab/FragPipe-Analyst-doc#18]
- Describe the issue or question:
Hi, I uploaded my diaNN output "report.pg_matrix.tsv" and "report.gg_matrix.tsv" into FragPipe analyst, but both of these two files are not compatible for analysis. I attached the warning from FragPipe analyst. What is the problem? Thank you!
![1705647499996](https://github.com/Nesvilab/FragPipe/assets/155048109/2a6cbb93-58ff-4552-bbbe-61e721232acb)

- Upload your log file
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**Comment by YeelonYeoh** [comment]
> * Describe the issue or question:
>   Hi, I uploaded my diaNN output "report.pg_matrix.tsv" and "report.gg_matrix.tsv" into FragPipe analyst, but both of these two files are not compatible for analysis. I attached the warning from FragPipe analyst. What is the problem? Thank you!
>   ![1705647499996](https://private-user-images.githubusercontent.com/155048109/297981448-2a6cbb93-58ff-4552-bbbe-61e721232acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODg3NTEsIm5iZiI6MTcwNTg4ODQ1MSwicGF0aCI6Ii8xNTUwNDgxMDkvMjk3OTgxNDQ4LTJhNmNiYjkzLTU4ZmYtNDU1Mi1iYmJlLTYxZTcyMTIzMmFjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwMTU0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjNhMGJlMjIxYTk0YzA4MTRlZjY3NjZjYWJlZTI4MWNkY2IwMjA1OGM1ZjRkOWRmMWE4YzA4ZTdiYjc2ZmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._ZqBW7hWh2Uyj-9BXxvcpAXLwrxAb3rfQBZQE91FyOI)
> * Upload your log file
>   (If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)
Please check that the formatting for the report file, especially the heading for each sample in which case is the file location, tallies with the ones in the file for experimental design.

**Comment by YeelonYeoh** [comment]
Hi, I want to analyse phosphoproteome data acquired using DDA with reference to the proteome data acquired using DIA. May I get advices for doing so? Perhaps you might refer me to the user's manuals or papers that describe the ways to do so.

**Comment by hsiaoyi0504** [comment]
@Amelia811 Sorry I missed this one. We didn't really support gg_matrix so please use pg_matrix. Meanwhile, would you mind sharing your file with me then I can take a look yihsiao@umich.edu

**Comment by hsiaoyi0504** [comment]
Closed since no response.

**Comment by hsiaoyi0504** [comment]
Closed. Replied in the email. There are errors in the experiment_annotation.tsv file.
