### ISSUE TITLE
How to analyse phosphoproteome data acquired using DDA with reference to the proteome data acquired using DIA?

### ISSUE THREAD

**Issue by YeelonYeoh** [Nesvilab/FragPipe-Analyst-doc#19]
Hi, I want to analyse phosphoproteome data acquired using DDA with reference to the proteome data acquired using DIA. May I get advices for doing so? Perhaps you might refer me to the user's manuals or papers that describe the ways to do so.

**Comment by hsiaoyi0504** [comment]
Closed since duplicated with monashProteomics/FragPipe-Analyst#90.
