### ISSUE TITLE
Fragpipe analyst normalisation has no effect for DIA data

### ISSUE THREAD

**Issue by TBDerm** [Nesvilab/FragPipe-Analyst-doc#22]
Hi all,

I'm running a proteomics experiment and noticed something about the 'no normalisation' / 'variance stabilizing normalisation' option in fragpipe analyst.

I'm using DIA intensity data (output from DIA-NN). I have two datasets: the whole set with all detected proteins, and a subset of ~45 proteins. There are 3 replicates of 2 conditions.

So the mystery lies here: I have tried uploading both the whole dataset and the sub-dataset, with and without the normalisation option. Regardless of dataset, normalisation has no effect on the outputted fold change and adjusted p-values. HOWEVER, a colleague has a similar situation: whole dataset (DIA-NN output) and a subset of certain proteins from this - when they try these different settings on Fragpipe analyst, normalisation makes no difference to the sub-dataset output, but when the whole dataset is inputted, selecting normalisation does produce different fold change values for some proteins, vs when no normalisation is selected.

So this has left us all confused, and our supervisors are suggesting we manually normalise the DIA-NN output before inputting it to fragpipe analyst. Does anyone else have suggestions on getting around this issue, or if it even is an issue? With the differences occurring only sometimes, I do not know if it is working as it should, or if there is a problem.

Does anyone know why fragpipe analyst is doing this, or how the built-in normalisation works? Any insights would be appreciated!

**Comment by hsiaoyi0504** [comment]
Thanks for the feedback. @TBDerm If you have the data and able to share with me yihsiao@umich.edu, I can take a look or I currently don't have much idea about it.

**Comment by hsiaoyi0504** [comment]
@TBDerm I think it fixed now. I realized that vsn was not applied for DIA previously. Would you mind checking it again?

**Comment by hsiaoyi0504** [comment]
Close given no response.

**Comment by veslugleynat** [comment]
Hi,
Thanks for fixing vsn for DIA data. Is it possible to manually replicate what it does to check my data please? Thanks!

**Comment by hsiaoyi0504** [comment]
@veslugleynat Can you elaborate a bit what's your request? I am confused.
