### ISSUE TITLE
Fragpipe analyst giving multiples of identical p-values

### ISSUE THREAD

**Issue by TBDerm** [Nesvilab/FragPipe-Analyst-doc#23]
Hi all,
I have recently uploaded a DIA intensity proteins dataset to fragpipe analyst, to get fold change and p-values. Contrary to other datasets I have analysed previously, this one is producing multiple identical p-values, so that when I make a volcano plot, there are several plateaus of points. Could anyone provide an explanation for this? Volcano plot is attached.
Thanks!

![image](https://github.com/Nesvilab/FragPipe-Analyst/assets/161644110/4cb0d60c-f37d-44b0-91a1-5a1d5ae5fbcb)

**Comment by hsiaoyi0504** [comment]
Thanks for the feedback. @TBDerm It's possible to have adjusted p-value or p-value the same. It's really typically when you have a comparison not really seeing difference like this case. I don't think that's really an issue of the program. Thanks.
