### ISSUE TITLE
Analyst not downloading main report file

### ISSUE THREAD

**Issue by TimKarr** [Nesvilab/FragPipe-Analyst-doc#24]
For last few days, cannot download report file (the other csv files do download). Error message, "site not available".

**Comment by hsiaoyi0504** [comment]
Thanks for the report. @TimKarr I tested a little bit but wasn't able to reproduce such issue now. Do you have some detailed description like which quantification strategy you are using? And are you using protein or peptide level reports as input? I need to have some more detailed info to find out the issue. Thanks.

**Comment by TimKarr** [comment]
Thanks@hsiaoyi0504, using latest version of Chrome on Windows 11. Successfully ran FP with some errors (e.g., the main matrix loads, the PCA plot works but not the volcano plots. When all functionalities work, the Report downloads as expected, but the incomplete FP webpage will not download the Report. The individual csv files do download. I hope this helps you troubleshoot this issue on my end. Thanks!

**Comment by hsiaoyi0504** [comment]
@TimKarr if the volcano plot doesn't work, it must be sth wrong. Would you mind sending me your files? yihsiao@umich.edu. I can take a look and see. Thanks.
