### ISSUE TITLE
Error in Sample CVs and Feature Numbers plot generation.

### ISSUE THREAD

**Issue by helloworld1631** [Nesvilab/FragPipe-Analyst-doc#27]
Hi, I am try to see the QC plots of my DIA quantification results. But Sample CVs and Feature Numbers panel report an error:
"An error has occurred. Check your logs or contact the app author for clarification.", while other QC plots look good. 
Where can I check my logs?

**Comment by hsiaoyi0504** [comment]
I think there is a bug introduced when I updated the version. I will fix it soon.

**Comment by hsiaoyi0504** [comment]
@helloworld1631 Should be fixed now. Can you try again in the v0.38?

**Comment by helloworld1631** [comment]
Thank you. Yes, now it works well.
