### ISSUE TITLE
Cannot download full dataset (.csv) on Fragpipe Analyst

### ISSUE THREAD

**Issue by SalDal93** [Nesvilab/FragPipe-Analyst-doc#28]
Using Fragpipe Analyst I am unable to download the full dataset (.csv) with an error appearing - downloaddata.htm couldn't download data, something went wrong. I have no issue downloading anything from other softwares/websites and can download any of the other .csv files on Analyst just not the full dataset.

**Comment by hsiaoyi0504** [comment]
@SalDal93 Could you describe it more about what you are referring to "error appearing"? Or share which files you uploaded with me yihsiao@umich.edu?
Usually I recommend people stop when seeing errors because it means something went wrong.

**Comment by hsiaoyi0504** [comment]
Closed since no response.
