### ISSUE TITLE
FragPipe-Analyst Error: 'label', 'condition', and/or 'replicate' columns are not present in the experimental design. 

### ISSUE THREAD

**Issue by awarsh** [Nesvilab/FragPipe-Analyst-doc#3]
Hi, 

When uploading my data in FragPipe-Analyst, the following error appears. 
![image](https://user-images.githubusercontent.com/119141129/208160640-7cef05ec-4c00-455b-8e04-d655fb93925d.png)

Here is the combinedprotein.tsv file and the .fp-manifest:
[combined_protein_tsv.xlsx](https://github.com/Nesvilab/FragPipe-Analyst/files/10248110/combined_protein_tsv.xlsx)
[lcms-files_2022-10-06_19-22-10_tsv.xlsx](https://github.com/Nesvilab/FragPipe-Analyst/files/10248111/lcms-files_2022-10-06_19-22-10_tsv.xlsx)

For this experiment, I have 4 conditions, and each condition was fractionated 8 times, so there are no replicates, which is why I left the replicate section blank. Any help in getting fragpipe-analyst to work properly would be appreciated. Thank you!

**Comment by hsiaoyi0504** [comment]
@awarsh Thanks for reporting the issue. There are few things here.
First, when I look at your lcms-files. It looks like you didn't specify the replicates. I am not sure if that's what you want.
Second, we are working on changes of the format for metadata (annotation). It will look like this in the future.
[lcms-files_2022-10-06_19-22-10.txt](https://github.com/Nesvilab/FragPipe-Analyst/files/10272563/lcms-files_2022-10-06_19-22-10.txt)

**Comment by hsiaoyi0504** [comment]
Closed for now because no further updates.
