### ISSUE TITLE
Formatting issues with experiment_annotation.tsv for DIA

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe-Analyst-doc#4]
Hello,
I have been testing FragPipe-Analyst with DIA data from DIA-NN and generating the experiment_annotation file as outlined in the DIA tutorial section here: https://github.com/MonashProteomics/FragPipe-Analyst/tree/main/docs
I have run into two formatting issues related to the experiment_annotation file. 

First, when I leave the full paths in the "file" column of the annotation and the DIA report (diann-output.pg_matrix.tsv), then i get the following error:
![image](https://user-images.githubusercontent.com/42681821/211102572-af98b32c-f4d9-4a15-86f8-12fbd2bfa066.png)
If I remove the path, leaving just the filename, in both the annotation file and DIA report, that message is gone.

Once that was resolved, I received a second error.
![image](https://user-images.githubusercontent.com/42681821/211102802-430c75d2-8725-4409-95ba-bffd1dca5903.png)
After testing, I realized that the labels in the sample_name and condition columns cannot start with numbers.  Once they were changed, the error message was resolved.

I have uploaded the original annotation file that I thought would be compatible, and the "fixed" annotation that allowed import of the data.
[experiment_annotation_fixed.txt](https://github.com/Nesvilab/FragPipe-Analyst/files/10363263/experiment_annotation_fixed.txt)
[experiment_annotation_original.txt](https://github.com/Nesvilab/FragPipe-Analyst/files/10363264/experiment_annotation_original.txt)

I hope this helps as you continue to develop Analyst, thank you for the developmental efforts!
Todd

**Comment by hsiaoyi0504** [comment]
@enonimos Thanks for the feedback. Could you send a copy of files you are using to yihsiao@umich.edu? I will take a look soon.

**Comment by hsiaoyi0504** [comment]
Based on my test sample_name column could contain values start with number, but condition column couldn't.

**Comment by hsiaoyi0504** [comment]
The fixes have been included in the MonashProteomics/FragPipe-Analyst@568a3c350783d0894a538996816b69a80773b3e4 and been available in v0.19.
For the `experiment_annotation.tsv` mentioned here, the file path doesn't match to the columns of protein group file. It might because the files have been moved after running the DIA workflow. Simply updated the `file` fixes the issue.

**Comment by enonimos** [comment]
I missed the differences in file path, sorry about that. Thank you.
