### ISSUE TITLE
Differential expression (limma) doesn't seem to use the median normalized data

### ISSUE THREAD

**Issue by rc2754** [Nesvilab/FragPipe-Analyst-doc#41]
The normalization option, whether it's "No normalization" or "Median centered", the DE_results.csv output is exactly the same...Why isn't median centered data being used as the input for limma.

Edit: the variance stabilizing normalization option too. It changes the density plot for the QC plots but it doesn't change anything about how the DE_results.csv is calculated.

**Comment by hsiaoyi0504** [comment]
@RC2754 Can you check which version of FragPipe-Analyst you are using? Also, what kind of data you are using? There is some versions ago we fixed #22.

**Comment by rc2754** [comment]
I was using (http://fragpipe-analyst.nesvilab.org/) because that's what shows up on Google, and what Fragpipe v20.0 links to.

But I just tried (https://fragpipe-analyst.org/) and same issue. No normalization or VSN gives exactly the same DE_results.csv

Label-free DDA data.

(https://fragpipe-analyst.org/) takes ages to load btw.

**Comment by hsiaoyi0504** [comment]
Do you use the imputation?

**Comment by hsiaoyi0504** [comment]
We recently fixed one here: https://github.com/MonashProteomics/FragPipe-Analyst/commit/04a456a566057ed60abf4b4773cc2baccf9e6df9. It should be in the v0.43 that we plan to release soon.

**Comment by rc2754** [comment]
Thanks. No I don't use imputation.
