### ISSUE TITLE
LQF_combined peptide analysis

### ISSUE THREAD

**Issue by RaquelVaya** [Nesvilab/FragPipe-Analyst-doc#44]
Hi, 
I'm trying to analyse my data os FBS on the fragpipe analist. I did my own reports with the last samples but im trying today with other sample (another output) and I cant do the LFQ of the peptide but it works with at the protein level. Ive just tryed the last samples and again the same but I know this program to the peptide report. I cannot redo it again. 

The error says: An error has occurred. Check your logs or contact the app author for clarification. The DIA report doesnt work at all. May have help please? 

Thanks for the attention.

Raquel

**Comment by hsiaoyi0504** [comment]
@RaquelIQS Did you fix it by yourself? Would you mind sharing your experience?

**Comment by RaquelVaya** [comment]
Hi Hsiao,

No, I haven't fixed it yet. Sorry for the delay; I was on holiday. I've
tried different parameters for the data and also used some extra data with
the same process but with more replicates, and it works with them but not
with this one. I'm not sure where the problem is. When I open the TSV
files, they appear the same in both cases. I'll send you some files for
reference. I'm using my own database based on UniProt.  I have three
samples of proteins that were attached to nanoparticles. These
nanoparticles differ in their composition, so there should be differences
in the proteins attached to them (the nanoparticles were incubated in a
blood sample). All the samples were processed simultaneously. My idea is to
use a heatmap for a relative quantification to visualize these differences.
I can provide any metadata you need. I'm quite new to this field and
entirely self-taught, so thank you for your patience and for providing the
information.

There is the same message on github, I will be keeping an eye on it.

Thank you,
