### ISSUE TITLE
C stack usage  1916096 is too close to the limit

### ISSUE THREAD

**Issue by luosupercool** [Nesvilab/FragPipe-Analyst-doc#48]
The error occurred when I uploaded the result file and comment file for TMTpro-18. BTW, I was running the application locally
![20240903](https://github.com/user-attachments/assets/cfd969a6-f39f-4692-a190-ae6864eb4c5c)

**Comment by hsiaoyi0504** [comment]
I think it's more specifically about your machine setting of the process. Check this: https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit.

**Comment by hsiaoyi0504** [comment]
Closed due to no response
