### ISSUE TITLE
Fragpipe-Analyst 500 internal server error 

### ISSUE THREAD

**Issue by Amelia811** [Nesvilab/FragPipe-Analyst-doc#49]
**- Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**
I can't open this site http://fragpipe-analyst.nesvilab.org/ since yesterday. My internet seems no problem, I can open google and other websites. Can you please fix it? Thank you.

**Comment by fcyu** [comment]
Thank you for the notification. Leo @hsiaoyi0504, could you take a look?

Thanks,

Fengchao

**Comment by hsiaoyi0504** [comment]
I restarted the sever. The underlying reason needs to be further looked into.

**Comment by Amelia811** [comment]
http://fragpipe-analyst.nesvilab.org/  was temporarily working yesterday and morning today. But now I can't open it again. And when it was working yesterday and today morning, analysis using MLE imputation seemed not working, the in process page was going forever. Can you please fix it?
Thank you.

**Comment by hsiaoyi0504** [comment]
@Amelia811 I restarted the server again, but what I can see in the log, some people seem to upload a very long list of different conditions causing infinite combinations of differential expression analysis. We will block this kind of requests in the future, but it might still take 1~2 weeks before we deploy such changes. Sorry for the inconvenience.

**Comment by Amelia811** [comment]
I see. So what is the limitation of condition numbers? How many beyond would cause troubles? Actually I have 8 conditions. But perseus type imputation seems no problems, I can get analyzed results quickly. But when changed it to MLE, it would be running forever. Then if I tried to refresh the page, I couldn't open the http://fragpipe-analyst.nesvilab.org/ anymore.  
Thank you.

**Comment by hsiaoyi0504** [comment]
@Amelia811 we haven't decided yet, but I didn't see the server offline now, so I guess you are not the one make the sever crash.

**Comment by Amelia811** [comment]
http://fragpipe-analyst.nesvilab.org/  can not working again. Today I used Perseus imputation, and everything went smoothly. However, when I switched to MLE, the process got stuck, just like it did the last time I posted here two weeks ago. It seems that when too many conditions are loaded and MLE imputation is used, the process can run indefinitely and eventually crash.

**Comment by hsiaoyi0504** [comment]
@Amelia811 Before I tried to restart the sever, I noticed the whole website is still working. Maybe if you can share the data with me then I can take a look further. yihsiao@umich.edu.

**Comment by hsiaoyi0504** [comment]
@Amelia811 So I dig a little more. I think the issue of MLE is generally expensive. The issue was discussed in https://github.com/rformassspectrometry/MsCoreUtils/issues/109. We will later move this method to the lower priority.
