### ISSUE TITLE
Incorrect calculations in Results Table but correct in Volcano plot

### ISSUE THREAD

**Issue by enonimos** [Nesvilab/FragPipe-Analyst-doc#5]
Hello,

As a continuation of my use of FP-Analyst with DIA data (from, #4), I have an observation where the values, such as FC, in the Result table are not correct based on the abundance values in the matrix.  However, when I visualize the Volcano plot, the x-axis FC values are what I would expect from the abundances.  I can illustrate the issue by displaying the names on the Volcano plot and then highlighting one of the most significant hits, gene name "Htt". Htt labeled from the Volcano plot is a the top-left, while Htt labeled after selecting the row in the Results table is in the non-significant region at the bottom.  Based on the individual abundances, Htt position at the top-left is correct.  I don't know if this is related to my "fixes" (#4) to the experiment_annotation file, or an unrelated issue.  Let me know if you would like additional files, I can upload to a link.
![image](https://user-images.githubusercontent.com/42681821/211105140-5af99744-1919-4c75-b852-d61fed2ad810.png)

Thank you,
Todd

**Comment by hsiaoyi0504** [comment]
As I mentioned in #4, I will take a look for the files soon, but based on what I have seen. The issue might happened if you updated some options but didn't click the "Start analysis" button again. I have tried to fix the issue recently and pushed the changes. Would you mind testing it again? Alternatively, when I got your files, I will check and fix the issue. Thank you!

**Comment by hsiaoyi0504** [comment]
The underlying issue is that DE procedures (including `add_rejectsions` function) mess up the order of proteins saved in `rowData`. The issue has been resolved in MonashProteomics/FragPipe-Analyst@cd023e5cd42d5392bd86745b244b7eeb452a4644 and will be available in v0.19. Please let me know if there is further issue. Thank you for the feedback!

**Comment by enonimos** [comment]
Thank you, I can confirm that v0.19 which I obtained from Github, correctly calculates log2 and DE stats. How long does it usually take for the changes to go live in the development or stable servers?

**Comment by hsiaoyi0504** [comment]
@enonimos Thank you for testing it. For the development server, I could update it real quick. For the production (stable) server, it might take 1-2 days to sync.
