### ISSUE TITLE
Error when running FragPipe-analyst

### ISSUE THREAD

**Issue by Lab123-prog** [Nesvilab/FragPipe-Analyst-doc#51]
**- 
[log_2024-09-16_18-54-51.txt](https://github.com/user-attachments/files/17020939/log_2024-09-16_18-54-51.txt)

Upload your log file**
(If a log file hasn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

Cannot work with the FragPipe Analyst
![1](https://github.com/user-attachments/assets/3d204653-fd99-4208-a33c-ea8c1c937006)
![2](https://github.com/user-attachments/assets/6d2e2d17-c6bd-4a83-a6be-8cfde99f0b0c)

Once the 2 files were added and press RUN, the above errors were generated.

Can you please let me know how I can deal with this situation.

Thank you

**Comment by hsiaoyi0504** [comment]
@Lab123-prog You might need to annotate the dataset to use FragPipe-Analyst. Could you share your `experiment_annotation.tsv` file?

**Comment by hsiaoyi0504** [comment]
Meanwhile, it looks like you upload `combined_peptide.tsv` rather than `combined_protein.tsv` file that required based on your configuration.

**Comment by Lab123-prog** [comment]
thank you so much, I will try it out

**Comment by Lab123-prog** [comment]
Sorry I still could not get it work.

![3](https://github.com/user-attachments/assets/27a34301-441a-41c6-a461-38ca4b285de7)
![4](https://github.com/user-attachments/assets/c30ecf03-d4dd-42eb-8230-32136f46f653)

**Comment by hsiaoyi0504** [comment]
Please post your experiment_annotation.tsv file. You need to have more than one sample for each condition, or differential expression might not work.

**Comment by Lab123-prog** [comment]
Please find the experimental annotation file 
[experiment_annotation.zip](https://github.com/user-attachments/files/17062500/experiment_annotation.zip)

**Comment by Lab123-prog** [comment]
Hi 
I would like to know whether the fragpipe data- the combined protein. tsv file we obtain is normalized or not .

**Comment by hsiaoyi0504** [comment]
It's not normalized before uploaded into FragPipe-Analyst

**Comment by hsiaoyi0504** [comment]
@Lab123-prog I checked your `experiment_annotation.tsv` As I mentioned, you need to have a least two samples for each condition or any DE might give the error.

**Comment by hsiaoyi0504** [comment]
Closed since no further response.
