### ISSUE TITLE
Error Analysing Data 

### ISSUE THREAD

**Issue by bigdog277** [Nesvilab/FragPipe-Analyst-doc#54]
Hello, I am trying to analyse some DIA data from fragpipe v22 but when I put in the files instructed it comes up with this error:
![fragpipeanalyist](https://github.com/user-attachments/assets/0184d1be-cc2e-4c2f-93d6-b60aace1b88d)

**Comment by hsiaoyi0504** [comment]
@bigdog277 Please share more details about the setting such as `experiment_annotation.tsv` or share the data with me yihsiao@umich.edu. It's impossible to help based on the information you provided.
