### ISSUE TITLE
Error analysing DIA data 

### ISSUE THREAD

**Issue by xbisteau** [Nesvilab/FragPipe-Analyst-doc#55]
Hello,  as others I have consistent error to analyse data. It works well up to end of september and reusing the same exact tables does not work anymore. The error message continuously appear. The tables of PG-matrix comes directly from DIANN and the annotation table was used before without any issues. What can I provide to show and resolve this error?

**Comment by xbisteau** [comment]
Looks like the changes in rownames from v0.43 to v1.0 cause the error   the v0.43 in local does not present any error while V1.3 does

**Comment by edwinjyoo** [comment]
Hi, I second what xbisteau is saying. My DIA analysis on fragpipe analyst was working great until the other day now I have errors like the following. Only the volcano plot works. Could someone help?

<img width="1920" alt="Screenshot 2024-10-22 at 8 14 37 AM" src="https://github.com/user-attachments/assets/e0fee3ca-5a64-43c2-9209-7d045ea7ee1b">

**Comment by hsiaoyi0504** [comment]
@xbisteau @edwinjyoo Are you doing analysis on the protein level or peptide level? I couldn't really reproduce the error using our internal testing data. It might also be good to share the data with me. yihsiao@umich.edu to reproduce the issue.

**Comment by edwinjyoo** [comment]
just sent data on other thread, protein level

**Comment by hsiaoyi0504** [comment]
@edwinjyoo There is some internal library implementation changed. You can't use merely numbers as the sample name.

**Comment by hsiaoyi0504** [comment]
@xbisteau Any update?

**Comment by edwinjyoo** [comment]
The updated experimental design that changed the names from numeric only ended up working thanks!
