### ISSUE TITLE
Issue with Absence/Presence Section Downloads

### ISSUE THREAD

**Issue by HibaSALIM** [Nesvilab/FragPipe-Analyst-doc#64]
Hello,

I am encountering an issue with downloading the “Filtered Results Table,” “Venn Plot,” and “UpSet Plot” in the Absence/Presence section while working with DIA results. The error is visible in the attached screenshot. I have thoroughly checked my files, and there doesn’t appear to be any problem with them.
Could you please assist me in resolving this issue?

Thank you for your support.

Hiba

<img width="630" alt="Issue with AbsencePresence Section Downloads" src="https://github.com/user-attachments/assets/ed528dab-4acf-4802-a5bf-2cbb758caebd">

**Comment by hsiaoyi0504** [comment]
We are investigating why the "Protein.Ids" is missing in this case.

**Comment by hsiaoyi0504** [comment]
Closed as well as https://github.com/MonashProteomics/FragPipe-Analyst/issues/103.
