### ISSUE TITLE
Fold Change Calculation Related Issues

### ISSUE THREAD

**Issue by luosupercool** [Nesvilab/FragPipe-Analyst-doc#66]
Dear fragpipe-analyst developers,

I have questions about the fold change in the DE_results.csv file obtained after the software does or does not use the VSN or median centering method.

I would like to understand the correlation between the values in the Imputed_matrix.csv file and the fold change. I am working with DIA data, and I wonder if the fold change (FC) is calculated using the raw quantification values from the report.pg_matrix.tsv file output by DIANN when no normalization method is specified, as I found that this corresponds with the DE_results.csv file. However, I have other questions, such as why different normalization methods result in different FCs in the DE_results. Could you please tell me the general data processing steps of fragpipe-analyst? Thank you very much!

luo

**Comment by hsiaoyi0504** [comment]
@luosupercool Thanks for asking the question, but I thought we explained the details in the manuscript:
https://pubs.acs.org/doi/10.1021/acs.jproteome.4c00294

> if the fold change (FC) is calculated using the raw quantification values from the report.pg_matrix.tsv file output by DIANN when no normalization method is specified

Depends on if you applied the imputation, if you don't have imputation applied, then t's simply based on raw quantification values.

> why different normalization methods result in different FCs in the DE_results.

Different normalization methods result in different input for imputation.
Even if you don't impute the data, the change of normalized matrix will definitely propagate to the differential expression analysis result.
