### ISSUE TITLE
Issue visualizing proteomics data acquired using DIA method

### ISSUE THREAD

**Issue by YeelonYeoh** [Nesvilab/FragPipe-Analyst-doc#67]
Hi, I am experiencing issues visualizing proteomics data acquired using DIA method. I received an error message saying 'duplicate 'row.names' are not allowed'. To make diagnosis easy, I have attached the protein file and the annotation file for reference.
[20231119_TEC_result_C_protein_matrix_rev_sp_removed.txt](https://github.com/user-attachments/files/18108418/20231119_TEC_result_C_protein_matrix_rev_sp_removed.txt)
[experiment_annotation.txt](https://github.com/user-attachments/files/18108424/experiment_annotation.txt)

**Comment by hsiaoyi0504** [comment]
@YeelonYeoh Are you sure your input is from FragPipe? 
See https://github.com/Nesvilab/FragPipeAnalystR/issues/14 as well.

**Comment by hsiaoyi0504** [comment]
Also, it looks like you have some empty lines in the end of the files which also causes the issue.

**Comment by YeelonYeoh** [comment]
Dear hsiaoyi0504, I used the analysis file generated from MSfragger where raw MS data was searched using the DIANN software. The version of FragPipe-Analyst used to visualise the analysis file results is v1.7. I would appreciate your help if you can help me to reformat my files to make them work. For your information, I managed to visualise my analysis file results using the previous version of FragPipe-Analyst. It is only recently I tried visualise my data again, I encountered error.

**Comment by hsiaoyi0504** [comment]
I updated the dev server to v1.8 and removed some empty lines in your files. Can you try it again?
[20231119_TEC_result_C_protein_matrix_rev_sp_removed.txt](https://github.com/user-attachments/files/18192712/20231119_TEC_result_C_protein_matrix_rev_sp_removed.txt)

**Comment by YeelonYeoh** [comment]
Dear hsiaoyi0504, I have managed to visualise my analysis file results based on the corrected file format. Thank you.

**Comment by hsiaoyi0504** [comment]
Thanks for checking that!
