### ISSUE TITLE
Indiscriminate error; see attached screen shot

### ISSUE THREAD

**Issue by akyocum** [Nesvilab/FragPipe-Analyst-doc#7]
Hi there,

First time user.  I have a DDA experiment result output from FragPipe (v19.1) trying to use FragPipe-Analyst.  Upload of both combined_protein.tsv and experiment_annotation.tsv complete, but does not perform any analysis.  Error is shown below that is within every possible window/tab:

![Screenshot 2023-01-31 at 10 26 51 AM](https://user-images.githubusercontent.com/124070201/215806716-e99edc06-2d39-4b6d-9808-2e21d5b51f94.png)

I'm not entirely sure how to even go about trouble shooting, can I access the logs?  I tried both servers.  The column sample names match in both, the metadata file matches the format posted in documentation.  I'm attaching the head of both for help (GIT doesn't support .tsv, so I'm attaching as txt.  

[experiment_annotation4FPanalyst.txt](https://github.com/Nesvilab/FragPipe-Analyst/files/10548183/experiment_annotation4FPanalyst.txt)

[combined_protein4FPanalyst.txt](https://github.com/Nesvilab/FragPipe-Analyst/files/10548186/combined_protein4FPanalyst.txt)

Thanks,
Anastasia

**Comment by akyocum** [comment]
Well, I figured it out.  It was my experimental design. Disregard please.

**Comment by hsiaoyi0504** [comment]
@akyocum Thank you. Sorry for the late reply. Just want to leave comments that might help other people meeting the same issue next time. In this case, replicate column is generated automatically as you can see, but it doesn't make sense to have replicate 30, 60, 90. Also, if you specify sample this way in FragPipe, you will only have six samples (bp_30, bp_60, bp_90, control_30, control_60, control_90) in the result combined_protein.txt.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/10943928/217573211-83bb4f10-056f-4e88-850c-5604dee953fb.png">

**Comment by MTM09386** [comment]
Hello, I am also getting this error but I do not understand why. 
![image](https://github.com/Nesvilab/FragPipe-Analyst/assets/140008083/16fe1e42-2a8c-4059-8435-d8c75315bdc3)

**Comment by MTM09386** [comment]
I get the same error even when I use the example data, so I don't think it is due to my annotation file. Any help would be appreciated.

Thank  you!

Molly

**Comment by hsiaoyi0504** [comment]
@MTM09386 Can you send me the file? yihsiao@umich.edu. I don't think I am able to reproduce the error you met with example file. Also, it would be better if you could only a separate issue.
